"""Code executor for LLM-generated VRPTW solver code.

This module executes Python code generated by the LLM and returns the solution.
It handles:
- Code validation and compilation
- Safe execution in isolated namespace with hard timeout
- Error extraction and reporting
- Solution extraction
"""

from __future__ import annotations

import ast
import logging
import sys
from dataclasses import dataclass
from typing import Any, Optional

logger = logging.getLogger(__name__)


@dataclass
class ExecutionResult:
    """Result of code execution."""
    
    success: bool
    routes: list[list[int]] | None = None
    total_distance: float | None = None
    vehicles_used: int | None = None
    error_message: str | None = None
    error_type: str | None = None
    stdout: str | None = None
    stderr: str | None = None
    runtime_sec: float = 0.0


@dataclass
class CodeValidation:
    """Validation result for generated code."""
    
    valid: bool
    syntax_error: str | None = None
    import_error: str | None = None
    function_missing: bool = False


def validate_code(code: str) -> CodeValidation:
    """Validate generated code for common issues.
    
    Checks:
    - Syntax errors
    - Required imports
    - Required solve() function
    """
    try:
        ast.parse(code)
    except SyntaxError as e:
        return CodeValidation(
            valid=False,
            syntax_error=f"Syntax error at line {e.lineno}: {e.msg}"
        )
    
    # Check for required imports
    required_imports = ["ortools", "pywrapcp"]
    missing_imports = []
    
    for imp in required_imports:
        if imp not in code:
            missing_imports.append(imp)
    
    if missing_imports:
        return CodeValidation(
            valid=False,
            import_error=f"Missing imports: {', '.join(missing_imports)}"
        )
    
    # Check for solve function
    if "def solve" not in code:
        return CodeValidation(
            valid=False,
            function_missing=True
        )
    
    return CodeValidation(valid=True)


def post_validate_and_fix(code: str) -> tuple[bool, str]:
    """Validate code and attempt auto-fixes for common LLM syntax errors.

    Tries in order:
    1. Parse as-is (baseline).
    2. Strip any leading indentation on every line.
    3. Normalize line endings (crlf → lf).

    Returns (fixed, code) — fixed is True if a fix was applied.
    """
    import textwrap

    # Try as-is first
    try:
        ast.parse(code)
        return False, code
    except SyntaxError:
        pass

    # Fix 1: Strip leading whitespace from every line.
    # LLM code blocks often have an extra indent level.
    stripped = textwrap.dedent(code)
    try:
        ast.parse(stripped)
        return True, stripped
    except SyntaxError:
        pass

    # Fix 2: Normalize CRLF → LF (Windows line endings can confuse the parser)
    normalized = stripped.replace("\r\n", "\n")
    try:
        ast.parse(normalized)
        return True, normalized
    except SyntaxError:
        pass

    return False, code


def extract_function(code: str, func_name: str = "solve") -> Optional[str]:
    """Extract a specific function from generated code.
    
    This helps isolate the solve function for inspection or modification.
    """
    lines = code.split("\n")
    func_lines = []
    in_function = False
    indent_level = 0
    
    for line in lines:
        if f"def {func_name}" in line:
            in_function = True
            indent_level = len(line) - len(line.lstrip())
            func_lines.append(line)
        elif in_function:
            current_indent = len(line) - len(line.lstrip())
            # Check if we've exited the function (dedented to same or less than function def)
            if line.strip() and current_indent <= indent_level:
                break
            func_lines.append(line)
    
    return "\n".join(func_lines) if func_lines else None


def execute_solve_code(
    code: str,
    solve_params: dict[str, Any],
    timeout: float = 60.0,
) -> ExecutionResult:
    """Execute LLM-generated solver code and return the solution.

    Uses subprocess isolation to cleanly kill the solver on timeout.
    ThreadPoolExecutor cannot interrupt blocking C calls (like OR-Tools),
    so subprocess is used instead — timeout kills the entire process tree.

    Args:
        code: The Python code containing the solve() function.
        solve_params: Dictionary of parameters to pass to solve().
        timeout: Maximum execution time in seconds.

    Returns:
        ExecutionResult with solution or error information.
    """
    import subprocess
    import tempfile
    import json as _json
    import os
    import time as _time

    start_time = _time.perf_counter()

    # Validate code first; try auto-fix for common LLM syntax issues before giving up
    validation = validate_code(code)
    if not validation.valid:
        fixed, code = post_validate_and_fix(code)
        if fixed:
            validation = validate_code(code)
        if not validation.valid:
            error_msg = (
                validation.syntax_error
                or validation.import_error
                or "Unknown validation error"
            )
            return ExecutionResult(
                success=False,
                error_message=error_msg,
                error_type="ValidationError",
                runtime_sec=_time.perf_counter() - start_time,
            )

    # Write code to a temp file and run it as a script.
    # Results are written to a temp JSON file so we don't depend on
    # stdout parsing. The subprocess is killed on timeout — no orphan threads.
    try:
        # Create result file first (so we have the path for the wrapper)
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".json", delete=False, encoding="utf-8"
        ) as f:
            result_path = f.name

        # Build wrapper with actual paths substituted in.
        # Use forward slashes — Windows \U \a \t \n etc are illegal
        # escape sequences in Python string literals, but / is always safe.
        wrapper = (
            _WRAPPER_CODE
            .replace(_PARAM_PLACEHOLDER, _json.dumps(solve_params))
            .replace(_RESULT_PLACEHOLDER, result_path.replace("\\", "/"))
        )

        # Write solver code + wrapper to temp file
        with tempfile.NamedTemporaryFile(
            mode="w", suffix=".py", delete=False, encoding="utf-8"
        ) as f:
            f.write(code)
            f.write("\n\n")
            f.write(wrapper)
            code_path = f.name

        proc = subprocess.Popen(
            [sys.executable, code_path],
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            cwd=os.getcwd(),
        )

        try:
            stdout_bytes, stderr_bytes = proc.communicate(timeout=timeout)
            stdout = stdout_bytes.decode("utf-8", errors="replace")
            stderr = stderr_bytes.decode("utf-8", errors="replace")
        except subprocess.TimeoutExpired:
            proc.kill()
            proc.wait()
            elapsed = _time.perf_counter() - start_time
            logger.warning(
                f"[CodeExecutor] Execution timed out after {timeout:.1f}s "
                f"(elapsed={elapsed:.1f}s), killed subprocess."
            )
            return ExecutionResult(
                success=False,
                error_message=f"Execution timed out after {timeout:.1f}s",
                error_type="TimeoutError",
                runtime_sec=elapsed,
            )
    finally:
        try:
            os.unlink(code_path)
        except OSError:
            pass

    elapsed = _time.perf_counter() - start_time

    # ── Priority 1: result file must exist AND be valid non-empty JSON ──────────
    result = None
    if os.path.exists(result_path):
        try:
            with open(result_path, encoding="utf-8") as f:
                raw = f.read().strip()
            if raw:
                result = _json.loads(raw)
            os.unlink(result_path)
        except Exception as e:
            logger.warning(
                f"[CodeExecutor] Result file read failed ({e}), "
                f"falling back to stdout. raw={repr(raw)[:100] if raw else 'EMPTY'}"
            )
            if os.path.exists(result_path):
                os.unlink(result_path)

    # ── Priority 2: stdout last line as JSON ───────────────────────────────────
    if result is None:
        stdout_clean = stdout.strip()
        if stdout_clean:
            # Try from last non-empty line backward
            lines = [ln.strip() for ln in stdout_clean.splitlines() if ln.strip()]
            for line in reversed(lines):
                try:
                    result = _json.loads(line)
                    break
                except Exception:
                    pass
            # Try entire stdout as one JSON blob
            if result is None:
                try:
                    result = _json.loads(stdout_clean)
                except Exception:
                    pass

    # ── Convert result dict → ExecutionResult ─────────────────────────────────
    if result is not None:
        if isinstance(result, dict):
            routes = result.get("routes") or []
            total_distance = result.get("total_distance") or 0.0
            vehicles_used = result.get("vehicles_used") or 0
        elif isinstance(result, list):
            # Some solvers return a list of routes directly
            routes = result
            total_distance = 0.0
            vehicles_used = len(routes)
        else:
            routes = []
            total_distance = float(result) if isinstance(result, (int, float)) else 0.0
            vehicles_used = 0

        if not routes:
            return ExecutionResult(
                success=False,
                error_message=f"solve() returned empty routes: {result}",
                error_type="EmptySolutionError",
                stdout=stdout,
                stderr=stderr,
                runtime_sec=elapsed,
            )
        return ExecutionResult(
            success=True,
            routes=routes,
            total_distance=total_distance,
            vehicles_used=vehicles_used,
            stdout=stdout,
            stderr=stderr,
            runtime_sec=elapsed,
        )

    # ── Priority 3: no usable result at all ────────────────────────────────────
    err_msg = stderr.strip() if stderr.strip() else stdout.strip()
    if not err_msg:
        err_msg = (
            f"No result produced. "
            f"stdout_len={len(stdout)}, stderr_len={len(stderr)}, "
            f"proc.returncode={proc.returncode}"
        )
    logger.error(
        f"[CodeExecutor] No parseable result. "
        f"stdout={stdout[:200]!r}, stderr={stderr[:200]!r}"
    )
    return ExecutionResult(
        success=False,
        error_message=err_msg,
        error_type="RuntimeError",
        stdout=stdout,
        stderr=stderr,
        runtime_sec=elapsed,
    )


# ── Inline wrapper injected into the temp script ──────────────────────────────
# Placeholders that will be replaced before writing to disk.
# Using two separate unique markers avoids format-string escaping issues
# with backslashes on Windows.
_PARAM_PLACEHOLDER = "__SOLVE_PARAMS_JSON__"
_RESULT_PLACEHOLDER = "__RESULT_FILE_PATH__"

_WRAPPER_CODE = """
import json as _json
import sys as _sys

if __name__ == "__main__":
    try:
        params = _json.loads('""" + _PARAM_PLACEHOLDER + """')
        result = solve(**params)
        with open('""" + _RESULT_PLACEHOLDER + """', "w", encoding="utf-8") as _f:
            _json.dump(result, _f)
        if result is None:
            _sys.exit(2)
    except Exception as _e:
        import traceback as _tb
        _sys.stderr.write(_tb.format_exc())
        _sys.exit(1)
"""


def extract_error_for_llm(execution_result: ExecutionResult) -> str:
    """Format error message for LLM to understand and fix.

    Returns a structured error message suitable for the self-debug prompt.
    """
    parts = []

    if execution_result.error_type:
        parts.append(f"Error Type: {execution_result.error_type}")

    if execution_result.error_message:
        parts.append(f"Error Message: {execution_result.error_message}")

    if execution_result.runtime_sec > 0:
        parts.append(f"Runtime: {execution_result.runtime_sec:.2f}s")

    if execution_result.stdout:
        stdout_lines = execution_result.stdout.strip().split("\n")
        if stdout_lines:
            parts.append(f"Stdout Output:\n{chr(10).join(stdout_lines[-10:])}")  # Last 10 lines

    return "\n\n".join(parts)


def build_execution_context(
    code: str,
    execution_result: ExecutionResult,
    instance_name: str,
) -> str:
    """Build context for self-debugging prompt.

    Returns a formatted string describing the execution state.
    """
    context_parts = [
        f"Instance: {instance_name}",
        f"Execution Success: {execution_result.success}",
        f"Runtime: {execution_result.runtime_sec:.2f}s",
    ]

    if execution_result.success:
        context_parts.extend([
            f"Vehicles Used: {execution_result.vehicles_used}",
            f"Total Distance: {execution_result.total_distance:.2f}",
            f"Routes: {len(execution_result.routes) if execution_result.routes else 0}",
        ])
    else:
        context_parts.extend([
            f"Error Type: {execution_result.error_type}",
            f"Error: {execution_result.error_message}",
        ])

    if execution_result.stdout:
        context_parts.append(
            f"Stdout (last 500 chars): {execution_result.stdout[-500:]}"
        )

    return "\n".join(context_parts)
